openapi: 3.0.0
info:
  title: IoT API
  version: 1.0.0
paths:
  /api/login:
    post:
      summary: User login
      description: Authenticates a user and returns a JWT token.
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  example: admin
                password:
                  type: string
                  example: secret123
      responses:
        '200':
          description: Successful login, returns JWT token
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  username:
                    type: string
        '401':
          description: Invalid username or password
  /api/logout:
    post:
      summary: User logout
      description: Logs out the user (client should discard the token manually).
      tags:
        - Auth
      responses:
        '200':
          description: Successful logout message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Logged out (client must discard token)
  /api/configuration:
    get:
      summary: Get device configuration
      description: >-
        Returns complete device configuration or filtered by topic/subtopic.
        Data is cached in Redis.
      tags:
        - Configuration
      parameters:
        - in: query
          name: topic
          schema:
            type: string
          description: Configuration topic (e.g., show-all, mqtt)
        - in: query
          name: subtopic
          schema:
            type: string
          description: Configuration subtopic (e.g., show-all)
      responses:
        '200':
          description: Configuration data
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal server error
    post:
      summary: Create/Update configuration
      description: Creates or updates device configuration. Requires authentication.
      tags:
        - Configuration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Configuration updated successfully
        '500':
          description: Failed to update configuration
    patch:
      summary: Partially update configuration
      description: Partially updates device configuration. Requires authentication.
      tags:
        - Configuration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Configuration updated successfully
        '404':
          description: Configuration not found
        '500':
          description: Failed to update configuration
  /api/data:
    get:
      summary: Get latest sensor data
      description: Returns the most recent values for temperature, voltage, humidity, etc.
      tags:
        - Sensor
      security:
        - bearerAuth: []
      responses:
        '200':
          description: JSON object with latest sensor values
          content:
            application/json:
              schema:
                type: object
                example:
                  temperature:
                    value: 25.1
                    timestamp: '2025-06-03T22:59:46.725Z'
                    type: temperature
                  voltage:
                    value: 230.5
                    timestamp: '2025-06-03T22:59:46.725Z'
                    type: voltage
                  humidity:
                    value: 60.4
                    timestamp: '2025-06-03T22:59:46.725Z'
                    type: humidity
        '401':
          description: Unauthorized - missing or invalid token
  /api/device/port/{portId}:
    get:
      summary: Get specific port information
      description: >-
        Returns information for a specific port. Data is cached in Redis for
        performance.
      tags:
        - Device Ports
      parameters:
        - in: path
          name: portId
          required: true
          schema:
            type: string
          description: Port identifier (e.g., XD1, XF1, X0, HMI)
      responses:
        '200':
          description: Port information array with fields and data
          content:
            application/json:
              schema:
                type: array
                items:
                  oneOf:
                    - type: array
                      items:
                        type: string
                    - type: object
        '401':
          description: Unauthorized - Authentication required
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                  detail:
                    type: string
                  type:
                    type: string
                  status:
                    type: integer
        '404':
          description: Port not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                  detail:
                    type: string
                  type:
                    type: string
                  status:
                    type: integer
        '500':
          description: Internal server error
  /api/device/ports:
    get:
      summary: Get all ports information
      description: Returns information for all device ports. Data is cached in Redis.
      tags:
        - Device Ports
      responses:
        '200':
          description: Object containing all ports data
          content:
            application/json:
              schema:
                type: object
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
  /api/diagnostics:
    get:
      summary: Get device diagnostics
      description: >-
        Returns device diagnostics including port statistics. Data is cached in
        Redis for performance.
      tags:
        - Diagnostics
      responses:
        '200':
          description: Diagnostics data with port statistics
          content:
            application/json:
              schema:
                type: object
                properties:
                  PortStatistics:
                    type: array
                    items:
                      type: object
                      properties:
                        key:
                          type: string
                        description:
                          type: string
                        channel:
                          type: string
                        severity:
                          type: string
                          enum:
                            - Info
                            - Warning
                            - Maintenance requested
                            - Fault
                            - Critical
                        type:
                          type: string
                          enum:
                            - Occured
                            - Cleared
                            - Active
                            - Inactive
                        time:
                          type: string
        '500':
          description: Internal server error
    put:
      summary: Update diagnostics data
      description: >-
        Updates device diagnostics and invalidates Redis cache. Requires
        authentication.
      tags:
        - Diagnostics
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                PortStatistics:
                  type: array
                  items:
                    type: object
      responses:
        '200':
          description: Updated diagnostics data
        '404':
          description: Diagnostics not found
        '500':
          description: Failed to update diagnostics
    post:
      summary: Add new diagnostic entry
      description: Adds a new port statistic entry to diagnostics. Requires authentication.
      tags:
        - Diagnostics
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                key:
                  type: string
                description:
                  type: string
                channel:
                  type: string
                severity:
                  type: string
                type:
                  type: string
                time:
                  type: string
      responses:
        '201':
          description: Diagnostic entry added successfully
        '400':
          description: Invalid request data
        '500':
          description: Failed to add diagnostic entry
    delete:
      summary: Clear all diagnostics
      description: Clears all port statistics. Requires authentication.
      tags:
        - Diagnostics
      responses:
        '200':
          description: Diagnostics cleared successfully
        '404':
          description: Diagnostics not found
        '500':
          description: Failed to clear diagnostics
  /api/device-info:
    get:
      summary: Get device information
      description: >-
        Returns basic information about the device. Data is cached in Redis for
        performance.
      tags:
        - Device
      responses:
        '200':
          description: JSON object containing device information
          content:
            application/json:
              schema:
                type: object
                example:
                  name: Device 1
                  location: Berlin
                  type: MVK Pro
                  model: A100
                  status: online
        '500':
          description: Internal server error
    put:
      summary: Update device information
      description: Updates the device information and invalidates Redis cache.
      tags:
        - Device
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              example:
                name: New Device Name
                location: Hanoi
                model: B200
                status: offline
      responses:
        '200':
          description: Updated device information
          content:
            application/json:
              schema:
                type: object
                example:
                  name: New Device Name
                  location: Hanoi
                  model: B200
                  status: offline
        '404':
          description: Device not found
        '500':
          description: Failed to update device
  /api/maintenance:
    get:
      summary: Get maintenance information
      description: >-
        Returns maintenance links, digital twin info, and IODD catalog. Data is
        cached in Redis.
      tags:
        - Maintenance
      responses:
        '200':
          description: Maintenance data including links and IODD catalog
          content:
            application/json:
              schema:
                type: object
                properties:
                  digitaltwin:
                    type: object
                    properties:
                      forms:
                        type: array
                        items:
                          type: object
                  backup_restore:
                    type: object
                  factorysettings:
                    type: object
                  firmware_update:
                    type: object
                  iodd_catalog:
                    type: object
                    properties:
                      ethIpv4:
                        type: array
                        items:
                          type: object
        '500':
          description: Internal server error
    put:
      summary: Update maintenance data
      description: Updates maintenance configuration. Requires authentication.
      tags:
        - Maintenance
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Updated maintenance data
        '404':
          description: Maintenance not found
        '500':
          description: Failed to update maintenance
  /api/maintenance/reboot:
    post:
      summary: Reboot device
      description: Triggers device reboot. Requires authentication.
      tags:
        - Maintenance
      responses:
        '200':
          description: Reboot initiated successfully
        '500':
          description: Failed to initiate reboot
  /api/maintenance/factorysettings:
    post:
      summary: Reset to factory settings
      description: Resets device to factory settings. Requires authentication.
      tags:
        - Maintenance
      responses:
        '200':
          description: Factory reset initiated successfully
        '500':
          description: Failed to initiate factory reset
  /api/maintenance/fwupdate:
    post:
      summary: Update firmware
      description: Initiates firmware update process. Requires authentication.
      tags:
        - Maintenance
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                firmware:
                  type: string
                  format: binary
      responses:
        '200':
          description: Firmware update initiated successfully
        '400':
          description: Invalid firmware file
        '500':
          description: Failed to initiate firmware update
  /api/picture:
    get:
      summary: Get device image
      description: Returns the device image file. Metadata is cached using Redis.
      tags:
        - Picture
      responses:
        '200':
          description: JPEG image of the device
          content:
            image/jpeg:
              schema:
                type: string
                format: binary
        '500':
          description: Failed to retrieve image
      headers:
        X-Image-Content-Type:
          description: Content type of the image
          schema:
            type: string
            example: image/jpeg
    put:
      summary: Clear image cache and return device image
      description: Clears cached metadata for the image in Redis and re-sends the file.
      tags:
        - Picture
      responses:
        '200':
          description: JPEG image re-sent after clearing cache
          content:
            image/jpeg:
              schema:
                type: string
                format: binary
        '500':
          description: Failed to update or re-send image
  /api:
    get:
      summary: Get Thing Description root metadata
      description: |
        Returns metadata following W3C Web of Things Thing Description standard.
        Response is dynamic depending on login status (`req.user`).
      tags:
        - Root
      responses:
        '200':
          description: Thing Description metadata with available API links
          content:
            application/json:
              schema:
                type: object
                properties:
                  context:
                    type: string
                    example: https://www.w3.org/2022/wot/td/v1.1
                  id:
                    type: string
                    example: http://localhost
                  title:
                    type: string
                    example: Sensor
                  version:
                    type: object
                    properties:
                      instance:
                        type: string
                        example: 1.0.0
                      model:
                        type: string
                        example: '58841'
                  created:
                    type: string
                    format: date-time
                  base:
                    type: string
                  security:
                    type: string
                    example: basic_sc
                  links:
                    type: array
                    items:
                      type: object
                      properties:
                        href:
                          type: string
                          example: /information
                        rel:
                          type: string
                          example: information
                        method:
                          type: string
                          example: GET
components: {}
tags:
  - name: Configuration
    description: Device configuration management
  - name: Device Ports
    description: Device port information and configuration
  - name: Diagnostics
    description: Device diagnostics and port statistics
  - name: Device
    description: Device information and metadata
  - name: Maintenance
    description: Device maintenance operations and IODD catalog
  - name: Picture
    description: APIs for fetching and updating the device image
